name: LobbyPVP
version: 'Release-16.4'
main: wozniaktv.lobbypvp.LobbyPVP
api-version: 1.19
authors: [ WoZniaK_TV ]
description: Simple and customizable LobbyPVP
commands:
  lpvpreload:
    description: "Reload the config of the Plugin"
    usage: /lpvpreload
    permission: "lobbypvp.reload"